### ISSUE TITLE
Disable scrolling and zooming on mobile view

### ISSUE THREAD

**Issue by robaxelsen** [robaxelsen/robaxelsen.github.io#7]
Svetlozar Kalchev posted on FB:
"Nice! I would disable scrolling and zooming, however. I can scroll and zoom on iOS in Safari. Don't know if this happens on Android."

**Comment by robaxelsen** [comment]
@Svetlozar, could you please check if it's better now? If not, please provide steps to reproduce, or a screenrecording etc.

**Comment by SvetlozarKalchev** [comment]
Nope, still the same. 

Change this:
`<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />`

to this:

`<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' name='viewport' />`

You can disable scrolling by canceling the touchmove event. 
`document.ontouchmove = function(e) { e.preventDefault(); }`

**Comment by robaxelsen** [comment]
Thanks, @SvetlozarKalchev! Implemented now, please verify on your end.

I had to change your ontouchmove suggestion slightly, by explicitly adding an even listener, and also stopping propagation.

**Comment by SvetlozarKalchev** [comment]
I can verify that both issues are fixed. Good job!
